version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "60081:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: "jc21/mariadb-aria:10.4"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql

  frontend:
    image: mine0702/openvidu-frontend
    restart: unless-stopped
    container_name: app_frontend
    expose:
      - "3000"
    stdin_open: true
    mem_limit: 512m

  backend:
    image: mine0702/openvidu-backend
    restart: unless-stopped
    container_name: app_backend
    stdin_open: true
    expose:
      - "8080" # 백엔드 서비스가 사용하는 포트, 외부에 노출하지 않음
    mem_limit: 512m
# networks:
#   default:
#     external:
#       name: nginx-proxy
