version: "3"
services:
  nginx:
    restart: always
    image: mine0702/openvidu-nginx
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # openvidu-server:
  #   image: openvidu/openvidu-server-kms:latest
  #   environment:
  #     - OPENVIDU_SECRET=633ehddbs
  #     - DOMAIN_OR_PUBLIC_IP=www.beevarium.site
  #     - KMS_URIS=["ws://kms:8888/kurento"]

  # kms:
  #   image: kurento/kurento-media-server:latest
  #   ports:
  #     - "8888:8888"

  frontend:
    image: mine0702/openvidu-frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  backend:
    image: mine0702/openvidu-backend
    container_name: app_backend
    ports:
      - 8080:8080
    # volumes:
    #   - /app/node_modules
    #   - ./backend:/app
    stdin_open: true
    mem_limit: 128m
