version: "3"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 80
      - 81
      - 443
    volumes:
      - /docker/nginx-proxy-manager/data:/data
      - /docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Asiz/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
